src/Ucommerce.Sitecore.Web/Css/Sitecore8/ucommerce-sitecore8.css

- 300px work better than 200px
- change following the one in main Ucommerce repo

300px tree, remainder for content

---

src/UCommerce.SiteCore.Installer/UCommerce.SiteCore.Installer.csproj
src/UCommerce.SiteCore.Installer/packages.config
src/UCommerce.Sitecore/UCommerce.Sitecore.csproj
src/UCommerce.Sitecore/packages.config
src/UCommerce.Sitecore92/UCommerce.Sitecore92.csproj
src/Ucommerce.Sitecore.Web/Css/Sitecore8/UI.css
src/Ucommerce.Sitecore.Web/UCommerce.Sitecore.Web.csproj
src/Ucommerce.Sitecore.Web/packages.config

Image preview was not places correctly, and overlapped the side menu.
These two changes seem to fix it.
image and "deselect" crosses both has to be changed to match.

imagePicker styling fix

---

src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/UCommerce.SiteCore.Installer/packages.config
src/Ucommerce.Sitecore.Web/Ucommerce.Sitecore.Web.csproj
src/Ucommerce.Sitecore.Web/packages.config
src/Ucommerce.Sitecore/Ucommerce.Sitecore.csproj
src/Ucommerce.Sitecore/packages.config
src/Ucommerce.Sitecore93/Ucommerce.Sitecore93.csproj
src/Ucommerce.Sitecore93/packages.config

See https://github.com/Ucommercenet/Ucommerce/pull/564 for background.

Update Ucommerce package refs to a published version

---

src/UCommerce.SiteCore.Installer/PostInstallationStep.cs

Fix: Delete unused sanitization dll's

---

src/UCommerce.SiteCore.Installer/SiteCoreInstallerLoggingService.cs

"Could not load file or assembly Ucommerce.Infrastructure"

fix: Package no longer fails with assembly file load exception.

---

src/UCommerce.SiteCore.Installer/SpeakSerialization/sitecore/client/uCommerce Applications/Catalogs/Catalogs.item
src/UCommerce.SiteCore.Installer/SpeakSerialization/sitecore/client/uCommerce Applications/Products/Products.item
src/UCommerce.SiteCore.Installer/SpeakSerialization/sitecore/client/uCommerce Applications/Promotions/Promotions Application.item
src/UCommerce.SiteCore.Installer/SpeakSerialization/sitecore/client/uCommerce Applications/Stores/Stores.item

- Fixed SPEAK apps (all of the vue ones were broken)
- Updated promotions app to use the vue app instead of webforms one

Sitecore node routing

---

src/UCommerce.SiteCore.Installer/SpeakSerialization/sitecore/client/uCommerce Applications/Orders/Orders Application.item
src/Ucommerce.Sitecore.sln

This is only the changes for the speak app to work.

feat: replace old speak app with new vue app

---

src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/UCommerce.SiteCore.Installer/packages.config
src/Ucommerce.Sitecore.Web/Ucommerce.Sitecore.Web.csproj
src/Ucommerce.Sitecore.Web/packages.config
src/Ucommerce.Sitecore/Ucommerce.Sitecore.csproj
src/Ucommerce.Sitecore/packages.config
src/Ucommerce.Sitecore93/Ucommerce.Sitecore93.csproj
src/Ucommerce.Sitecore93/app.config
src/Ucommerce.Sitecore93/packages.config

feat: Upgraded ucommerce to 9.5.1

---

src/UCommerce.SiteCore.Installer/ConfigurationTransformations/updateAssemblyBinding.config
src/UCommerce.SiteCore.Installer/Steps/MoveUcommerceBinaries.cs
tools/Deploy/uCommerce.Sitecore.ps1

This is a reversal of the following two commits
https://github.com/Ucommercenet/Ucommerce.Sitecore/commit/0922aac0b68c38dd7d50cc2a2c14e29c142e6bc3
https://github.com/Ucommercenet/Ucommerce.Sitecore/commit/64d284a0508f2efd2bc6bbafddaac5caaae643b0

Reverse headless app experiment.

---

src/Ucommerce.Sitecore.Cli/Program.cs
src/Ucommerce.Sitecore.Cli/Properties/AssemblyInfo.cs
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj
src/Ucommerce.Sitecore.Cli/packages.config
src/Ucommerce.Sitecore.sln

Setup a new project for the CLI sitecore installer with NConsole nuget package

Ucommerce Sitecore CLI project with CliFx - Initial commit

---

src/Ucommerce.Sitecore.Cli/Commands/Database.cs
src/Ucommerce.Sitecore.Cli/Commands/Install.cs
src/Ucommerce.Sitecore.Cli/Commands/Upgrade.cs
src/Ucommerce.Sitecore.Cli/Program.cs
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj

Command scaffolding. Right now the upgrade command inherits the install command and overrides the executon, there might be a better way

Initial command scaffolding

---

src/UCommerce.SiteCore.Installer/Steps/IStep.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj

Interface for the steps to implement, used to run each step

Interface for the steps to implement, used to run each step

---

src/UCommerce.SiteCore.Installer/PostInstallationStep.cs
src/UCommerce.SiteCore.Installer/SitecoreInstallationConnectionStringLocator.cs

Change Sitecore connection string locator to take a connection string in constructor instead of using web configurations

Chore: Change SitecoreInstallationConnectionStringLocator.cs

---

src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/Ucommerce.Sitecore.Cli/Commands/Install.cs
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj

Creating the initial install step, which is responsible for running all steps related to the install commmand.

chore: create install step

---

src/UCommerce.SiteCore.Installer/Steps/UpdateUCommerceAssemblyVersionInDatabase.cs

Move this step from the old installer to the new. All the old steps can be found at https://github.com/Ucommercenet/Ucommerce.Sitecore/tree/develop/src/UCommerce.SiteCore.Installer/Steps

Chore/sc 18412/create updateucommerceassemblyversionindatabase

---

src/UCommerce.SiteCore.Installer/Steps/DatabaseStep.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/Ucommerce.Sitecore.Cli/Commands/Database.cs

The initial database step that runs all of the other database steps

Chore/sc 18452/create first db step

---

src/UCommerce.SiteCore.Installer/PostInstallationStep.cs
src/UCommerce.SiteCore.Installer/Steps/MoveFile.cs
src/UCommerce.SiteCore.Installer/Steps/MoveResourceFiles.cs

This PR is to Move resource Step .

chore: move resource files

---

src/UCommerce.SiteCore.Installer/PostInstallationStep.cs
src/UCommerce.SiteCore.Installer/Steps/DeleteFile.cs
src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Steps/MoveUcommerceBinaries.cs
src/UCommerce.SiteCore.Installer/Steps/PreRequisitesChecker.cs

I out-commented some code in other files that kept me from building, since the constructor is changed in the delete file step.. Tested the step using the install command and it works fine
That means that the actual changes are made in the DeleteFile.cs, and the rest are just outcommenting and code cleanup messing with git

Chore: Create DeleteFile step

---

src/UCommerce.SiteCore.Installer/Steps/CopyFile.cs
src/Ucommerce.Sitecore.sln.DotSettings

This Pr involves adapting the CopyFile step to the new cli tool, I also have a separate commit with a dotSettings file.
The dotSettings file is used to align styling with other project, as it helps with auto cleanup.

chore: adapt CopyFile step

---

src/UCommerce.SiteCore.Installer/Steps/MoveDirectoryIfTargetExist.cs

this PR is made to move directory if target exist step

chore: move directory if target exist step

---

src/UCommerce.SiteCore.Installer/Steps/MoveFileIfDoesntExist.cs

This PR for move file if doesn't exist step

chore: move file if doesn't exist

---

src/Ucommerce.Sitecore.Cli/App.config
src/Ucommerce.Sitecore.Cli/Commands/Database.cs
src/Ucommerce.Sitecore.Cli/Logging/CliLogger.cs
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj
src/Ucommerce.Sitecore.Cli/packages.config

feat: add a simple console logger for debugging

---

src/UCommerce.SiteCore.Installer/Steps/DatabaseStep.cs
src/UCommerce.SiteCore.Installer/Steps/InstallDatabase.cs
src/Ucommerce.Sitecore.Cli/App.config
src/Ucommerce.Sitecore.Cli/Commands/Database.cs

feat: create step for installing the ucommerce database

---

src/UCommerce.SiteCore.Installer/Steps/MoveUcommerceBinaries.cs
src/Ucommerce.Sitecore.Cli/README.md
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj

This Pr includes a readme file with an explanation of how to test a step. 
It also includes a separate commit with some boyscouting to fix up the MoveUcommerceBinaries step again.

Chore/sc 18455/document a way to test the cli commands

---

src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Steps/PreRequisitesChecker.cs
src/Ucommerce.Sitecore.Cli/Commands/Install.cs

Added logger to installation step, it is useful for debugging faster

Chore: create PreRequisitesChecker step

---

src/UCommerce.SiteCore.Installer/Steps/GuidExtensions.cs

Just changed som variables to var, also checked that it works using the cli
Most of the changes are just code cleanup

Chore: create GuidExtensions step

---

src/UCommerce.SiteCore.Installer/Steps/DatabaseStep.cs
src/UCommerce.SiteCore.Installer/Steps/InstallDatabaseSitecore.cs

Created the step and also added it to the DatabaseStep step.
sc-18398

feat: create InstallDatabaseSitecore step

---

src/UCommerce.SiteCore.Installer/Steps/InitializeObjectFactory.cs

this PR for initialize object factory step

chore: initialize object factory step

---

src/UCommerce.SiteCore.Installer/Steps/EnableSitecoreCompatibilityApp.cs

this PR for enable sitecore compatibility app step

chore: enable sitecore compatibility app step

---

src/UCommerce.SiteCore.Installer/Steps/PreRequisitesChecker.cs
src/Ucommerce.Sitecore.Cli/Logging/CliLogger.cs

Added two Log methods for formatting the text better, and added a few more details to information and error logging like color and log level
sc-18456

Chore/sc 18456/create proper console logger

---

src/UCommerce.SiteCore.Installer/Steps/EnableApp.cs
src/UCommerce.SiteCore.Installer/Steps/EnableSitecoreCompatibilityApp.cs
src/UCommerce.SiteCore.Installer/Steps/UpgradeAppIfEnabled.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj

Two steps added:
* EnableApp - Enable an app
* UpgradeAppIfEnabled - Ensure an enabled app gets upgraded
sc-18551

refactor: create general step for enabling apps

---

src/Ucommerce.Sitecore.Cli/Logging/CliLogger.cs

The output was too long
sc-18572

chore: log steps on a single line

---

src/UCommerce.SiteCore.Installer/Steps/MergeConfig.cs
src/UCommerce.SiteCore.Installer/Steps/Transformation.cs

Also changed a small spelling mistake in the Transform class

chore: MergeConfig should throw exception in addition to logging

---

src/UCommerce.SiteCore.Installer/Steps/ComposeMoveSitecoreConfigIncludes.cs
src/UCommerce.SiteCore.Installer/Steps/MoveFileIf.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj

Created a new MoveFileConditional.cs step, which only moves the file if the given function returns true. This shortens the ComposeMoveSitecoreConfigIncludes.cs a lot.
sc-18581

chore: create a conditional MoveFile

---

src/UCommerce.SiteCore.Installer/Steps/AddClientDependencyBundlesToIgnoreUrlPrefixes.cs
src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj

Created a installation step which adds /api/v1 to sitecore.config dependencies
sc-17003

fix: Sitecore 10.2 headless authorization error

---

src/UCommerce.SiteCore.Installer/Steps/AddHeadlessToIgnoreUrlPrefixes.cs
src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj

renamed class to better describe its purpose

chore: renamed class to better describe its purpose

---

src/UCommerce.SiteCore.Installer/Steps/CreateApplicationShortcuts.cs

Cleans up the create application shortcuts step

chore: clean create application shortcut step

---

src/UCommerce.SiteCore.Installer/Steps/CreateApplicationLaunchButton.cs

Did a code cleanup and set variables to var
sc-18387

chore: clean up CreateApplicationLaunchButton.cs

---

src/UCommerce.SiteCore.Installer/Steps/RemoveUCommerceApplicationLaunchButton.cs

Cleans the remove ucommerce application launch button step
sc-18408

chore: clean remove ucommerce application launch button step

---

src/UCommerce.SiteCore.Installer/Steps/CreateSpeakApplications.cs

Did a code cleanup, changed variables to var and added braces to if and while
sc-18390

chore: clean up CreateSpeakApplications.cs

---

src/UCommerce.SiteCore.Installer/Steps/AddTitleToCommerceSpeakAppsSection.cs

Did a code cleanup, changed variables to var and added braces to if and while
sc-18385

chore: clean up AddTitleToCommerceSpeakAppsSection.cs

---

src/UCommerce.SiteCore.Installer/Steps/BackupFile.cs
src/UCommerce.SiteCore.Installer/Steps/CopyFile.cs
src/UCommerce.SiteCore.Installer/Steps/DeleteDirectory.cs
src/UCommerce.SiteCore.Installer/Steps/DeleteFile.cs
src/UCommerce.SiteCore.Installer/Steps/InitializeObjectFactory.cs
src/UCommerce.SiteCore.Installer/Steps/InstallDatabaseSitecore.cs
src/UCommerce.SiteCore.Installer/Steps/InstallDatabaseUcommerce.cs
src/UCommerce.SiteCore.Installer/Steps/MergeConfig.cs
src/UCommerce.SiteCore.Installer/Steps/MoveDirectory.cs
src/UCommerce.SiteCore.Installer/Steps/MoveDirectoryIfTargetExist.cs
src/UCommerce.SiteCore.Installer/Steps/MoveFile.cs
src/UCommerce.SiteCore.Installer/Steps/MoveFileIfDoesntExist.cs
src/UCommerce.SiteCore.Installer/Steps/MoveFileIfTargetExist.cs
src/UCommerce.SiteCore.Installer/Steps/RenameConfigDefaultFilesToConfigFilesStep.cs
src/UCommerce.SiteCore.Installer/Steps/SeperateConfigSectionInNewFile.cs
src/UCommerce.SiteCore.Installer/Steps/SitecorePreRequisitesChecker.cs
src/UCommerce.SiteCore.Installer/Steps/UpdateUCommerceAssemblyVersionInDatabase.cs

chore: remove unneeded async form Run method

---

src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Steps/MoveResourceFiles.cs

Changed directory name and installStep input
sc-18603

chore: Change basepaths in MoveResourceFiles to sitecorepath

---

src/UCommerce.SiteCore.Installer/Steps/InstallStep.cs
src/UCommerce.SiteCore.Installer/Steps/MoveUcommerceBinaries.cs

Changed basepaths to sitecorepaths
sc-18602

chore: Change basepaths in MoveUcommerceBinaries to sitecorepath

---

src/Ucommerce.Sitecore.Cli/Commands/Upgrade.cs

makes the changes necessary to have an upgrade command
sc-18442

feature: upgrade command

---

src/UCommerce.SiteCore.Installer/FileExtensions/DirectoryExtensions.cs

To add clarity in the future, xml documentation should be added to the DirectoryInfo extension methods
sc-18628

chore: Add xml-documentation for the DirectoryInfo extension methods

---

src/Ucommerce.Sitecore.Install/packages.config

adds missing packages.config file

fix: add packages config

---

build/Build.cs

In order to be able to start changing build for
building the new package structure, we need to get rid
of all the warnings in the code.
sc-18622

fix: build has many inspection errors

---

src/UCommerce.SiteCore.Installer/Ucommerce.Sitecore.Installer.csproj
src/UCommerce.SiteCore.Installer/packages.config
src/Ucommerce.Sitecore.Cli/Ucommerce.Sitecore.Cli.csproj
src/Ucommerce.Sitecore.Cli/packages.config
src/Ucommerce.Sitecore.Install.Steps/Ucommerce.Sitecore.Install.Steps.csproj
src/Ucommerce.Sitecore.Install.Steps/packages.config
src/Ucommerce.Sitecore.Install/Ucommerce.Sitecore.Install.csproj
src/Ucommerce.Sitecore.Install/packages.config
src/Ucommerce.Sitecore.Web/Ucommerce.Sitecore.Web.csproj
src/Ucommerce.Sitecore.Web/packages.config
src/Ucommerce.Sitecore/Ucommerce.Sitecore.csproj
src/Ucommerce.Sitecore/packages.config
src/Ucommerce.Sitecore93/Ucommerce.Sitecore93.csproj
src/Ucommerce.Sitecore93/packages.config

Upgrades ucommerce dependencies so the installer will install the latest version of Ucommerce.

Upgrade ucommerce dependency

---

src/Ucommerce.Sitecore.Cli/Commands/Install.cs
src/Ucommerce.Sitecore.Install.Steps/ComposeMoveSitecoreConfigIncludes.cs
src/Ucommerce.Sitecore.Install.Steps/DatabaseInstallStep.cs
src/Ucommerce.Sitecore.Install.Steps/InstallStep.cs
src/Ucommerce.Sitecore.Install.Steps/SitecoreDatabasePreRequisitesChecker.cs
src/Ucommerce.Sitecore.Install.Steps/SitecoreInstallPreRequisitesChecker.cs
src/Ucommerce.Sitecore.Install.Steps/Ucommerce.Sitecore.Install.Steps.csproj

Cleaned up the installation step, and seperated the prerequisite checks into two, to further separate DB logic and install logic
sc-18674

chore: installation step cleanup

---

src/Ucommerce.Sitecore.Cli/Commands/Install.cs
src/Ucommerce.Sitecore.Cli/Commands/Upgrade.cs

chore: added descriptions to the install and upgrade commands

---

src/Ucommerce.Sitecore.Cli/Commands/Install.cs

Changed the starting message slightly, and added a small list of instructions for installing the package at the end of the CLI process. Below is an image showing how it looks right now with only the first and last message.
sc-18691

chore: add "Install sitecore package" message

---

src/Ucommerce.Sitecore.Cli/Commands/Install.cs

Adds the install step back to the install command

fix: install step was out commented
